# Generated by Django 4.1.7 on 2023-03-12 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Foodie_Zone', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partner',
            options={'verbose_name_plural': 'Partners'},
        ),
    ]
