# Generated by Django 4.1.7 on 2023-03-12 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Foodie_Zone', '0004_partner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partner',
            options={},
        ),
    ]
