# Generated by Django 4.1.7 on 2023-03-12 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Foodie_Zone', '0005_alter_partner_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Partner',
        ),
    ]
