# Generated by Django 4.1.7 on 2023-03-12 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Foodie_Zone', '0016_items'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Items',
        ),
    ]
