# Generated by Django 4.1.7 on 2023-03-13 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Foodie_Zone', '0020_customer_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('us_id', models.CharField(max_length=15)),
                ('us_name', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=25)),
                ('prob_whom', models.CharField(max_length=20)),
                ('problem', models.CharField(max_length=200)),
            ],
        ),
    ]
