# Generated by Django 4.1.7 on 2023-03-28 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Foodie_Zone', '0023_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='image',
            field=models.ImageField(upload_to='media/item'),
        ),
    ]
