# Generated by Django 4.1.7 on 2023-03-29 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Foodie_Zone', '0024_alter_items_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='image',
            field=models.ImageField(null=True, upload_to='item'),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cust', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Foodie_Zone.customer')),
                ('Item', models.ManyToManyField(to='Foodie_Zone.items')),
            ],
        ),
    ]
