# Generated by Django 4.1.7 on 2023-03-31 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Foodie_Zone', '0028_alter_cart_session_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='session_key',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
