# Generated by Django 4.1.7 on 2023-04-01 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Foodie_Zone', '0030_payment_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='paym',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Foodie_Zone.payment'),
        ),
    ]
