# Generated by Django 4.1.7 on 2023-04-06 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Foodie_Zone', '0031_alter_order_paym'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
