# Generated by Django 4.1.7 on 2023-04-06 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Foodie_Zone', '0032_delete_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('1', 'Ordered'), ('2', 'In kitchen'), ('3', 'Out for delivery'), ('4', 'Delivered')], default='1', max_length=1)),
                ('payment_status', models.CharField(choices=[('1', 'Pending'), ('2', 'Payment Done')], default='1', max_length=1)),
                ('add', models.TextField(max_length=100)),
                ('cart_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Foodie_Zone.cartitem')),
                ('cart_item_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Foodie_Zone.cartitem_item')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Foodie_Zone.customer')),
                ('paym', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Foodie_Zone.payment')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Foodie_Zone.restaurant')),
            ],
        ),
    ]
