# Generated by Django 4.1.7 on 2023-04-06 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Foodie_Zone', '0033_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cart_item_item',
        ),
    ]
