# Generated by Django 4.1.7 on 2023-04-09 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Foodie_Zone', '0034_remove_order_cart_item_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='mo_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='add',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
