# Generated by Django 4.1.7 on 2023-04-09 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Foodie_Zone', '0035_order_mo_no_order_name_alter_order_add'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('1', 'Ordering'), ('2', 'Ordered'), ('3', 'In kitchen'), ('4', 'Out for delivery'), ('5', 'Delivered')], default='1', max_length=1),
        ),
    ]
