# Generated by Django 4.1.7 on 2023-04-09 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Foodie_Zone', '0036_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('1', 'Pending'), ('2', 'Paid')], default='1', max_length=1),
        ),
    ]
