# Generated by Django 4.1.7 on 2023-04-09 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Foodie_Zone', '0037_alter_order_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='Cust',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='cart1',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='item',
        ),
        migrations.RemoveField(
            model_name='cartitem_item',
            name='cart_item',
        ),
        migrations.RemoveField(
            model_name='cartitem_item',
            name='item',
        ),
        migrations.RemoveField(
            model_name='order',
            name='cart_item',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='paym',
        ),
        migrations.RemoveField(
            model_name='order',
            name='restaurant',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='customer',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
        migrations.DeleteModel(
            name='CartItem_Item',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
