# Generated by Django 4.1.7 on 2023-04-09 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Foodie_Zone', '0038_remove_cartitem_cust_remove_cartitem_cart1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id1', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('session_key', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cust', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Foodie_Zone.customer')),
                ('cart1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Foodie_Zone.cart')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_mode', models.CharField(choices=[('1', 'Online Payment'), ('2', 'COD')], default='1', max_length=1)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Foodie_Zone.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('1', 'Ordering'), ('2', 'Ordered'), ('3', 'In kitchen'), ('4', 'Out for delivery'), ('5', 'Delivered')], default='1', max_length=1)),
                ('payment_status', models.CharField(choices=[('1', 'Pending'), ('2', 'Paid')], default='1', max_length=1)),
                ('add', models.TextField(max_length=100, null=True)),
                ('name', models.CharField(max_length=50, null=True)),
                ('mo_no', models.IntegerField(null=True)),
                ('cart_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Foodie_Zone.cartitem')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Foodie_Zone.customer')),
                ('paym', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Foodie_Zone.payment')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Foodie_Zone.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('cart_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Foodie_Zone.cartitem')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Foodie_Zone.items')),
            ],
        ),
        migrations.AddField(
            model_name='cartitem',
            name='item',
            field=models.ManyToManyField(through='Foodie_Zone.CartItem_Item', to='Foodie_Zone.items'),
        ),
    ]
