# Generated by Django 4.1.7 on 2023-04-09 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Foodie_Zone', '0041_alter_cart_id1_alter_cart_session_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='i',
            field=models.ImageField(max_length=12, null=True, upload_to=''),
        ),
    ]
