# Generated by Django 4.1.7 on 2023-04-09 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Foodie_Zone', '0042_cart_i'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='i',
        ),
        migrations.AlterField(
            model_name='cart',
            name='id1',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='session_key',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
